// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8RlS1ERFJ4Qw5QfqMT7jTblq6irE8X6g',
    appId: '1:1060797260335:web:89104932bbb518ae501cda',
    messagingSenderId: '1060797260335',
    projectId: 'myacc-8dd3c',
    authDomain: 'myacc-8dd3c.firebaseapp.com',
    storageBucket: 'myacc-8dd3c.appspot.com',
    measurementId: 'G-NER03F01PG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH49QWMQBdu-wpBxg-jvHHPmTB5iQ-fuQ',
    appId: '1:1060797260335:android:cb20bdad02d8622b501cda',
    messagingSenderId: '1060797260335',
    projectId: 'myacc-8dd3c',
    storageBucket: 'myacc-8dd3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAycSYKvQqrtWHzBb4FcpAMBlD8H_nmqnE',
    appId: '1:1060797260335:ios:de0e24c0894faa3a501cda',
    messagingSenderId: '1060797260335',
    projectId: 'myacc-8dd3c',
    storageBucket: 'myacc-8dd3c.appspot.com',
    iosClientId: '1060797260335-o5igvphtf017jol6nv39m84beogub808.apps.googleusercontent.com',
    iosBundleId: 'com.example.myacc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAycSYKvQqrtWHzBb4FcpAMBlD8H_nmqnE',
    appId: '1:1060797260335:ios:de0e24c0894faa3a501cda',
    messagingSenderId: '1060797260335',
    projectId: 'myacc-8dd3c',
    storageBucket: 'myacc-8dd3c.appspot.com',
    iosClientId: '1060797260335-o5igvphtf017jol6nv39m84beogub808.apps.googleusercontent.com',
    iosBundleId: 'com.example.myacc',
  );
}
